[build]
  publish = "build"
  command = "npm install && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  CI = "false"
  REACT_APP_SUPABASE_URL = "tu_supabase_url_produccion"
  REACT_APP_SUPABASE_ANON_KEY = "tu_supabase_anon_key_produccion"

[context.deploy-preview.environment]
  CI = "false"
  REACT_APP_SUPABASE_URL = "tu_supabase_url_staging"
  REACT_APP_SUPABASE_ANON_KEY = "tu_supabase_anon_key_staging"
